### ISSUE TITLE
croatian: additional lines missing

### ISSUE THREAD

**Issue by PeterTheOne** [Copywrongs-Gang/Copywrongs2#16]
Some of the newer lines are missing in the croatian translation, see: https://github.com/Copywrongs-Gang/Copywrongs2/blob/gh-pages/_data/croatian.yml .

@Aktron: Could you translate them? :)

**Comment by PeterTheOne** [comment]
Also please update your translation of these lines: 9112b227530d01d130cf1ab7def8ca551fc7ac4e

**Comment by PeterTheOne** [comment]
use this pad: https://titanpad.com/copywrongs-hr

**Comment by Aktron** [comment]
We made the most from what we could from the pad. Hopefully it would work.

**Comment by PeterTheOne** [comment]
I will merge this: #32
