### ISSUE TITLE
Website fonts do not support common characters

### ISSUE THREAD

**Issue by Putr** [Copywrongs-Gang/Copywrongs2#19]
Hi! As mentioned in my pull request fonts on the website do not support basic chars of many Slavic languages - Slovenian, Croatian, Czech etc. 

Czech translation for example looks really bad on the website. There are even more than the basic 'š', 'č' 'ž' and 'đ' missing. 

This needs to be fixed, because for an pan-European campaign this is quite embarrassing :/

**Comment by PeterTheOne** [comment]
I agree, but I can't promise that we are going to change at this point.

Can you recommend similar fonts that look good? Someone said we should use https://www.google.com/fonts/specimen/Noto+Serif .

**Comment by c3o** [comment]
That was my mistake when converting the fonts to webfonts – I've now replaced them with versions with more characters: https://github.com/Copywrongs-Gang/Copywrongs2/commit/5d48e3e2a88da2e9c2fa1d156b9eeb6797bde482

Do all languages now work after a shift-reload?

**Comment by Putr** [comment]
Yes, thank you!

**Comment by PeterTheOne** [comment]
Nice! :)
