### ISSUE TITLE
Greek: Update translation

### ISSUE THREAD

**Issue by PeterTheOne** [Copywrongs-Gang/Copywrongs2#25]
Please update your translation of these lines if you can: 9112b22

/cc: @pressPPGr

**Comment by Simos-Dalkyriadis** [comment]
Updates to the requested lines and some corrections from previous
translation for the _greek.yml_
See attachment

2015-06-10 15:42 GMT+03:00 Peter Grassberger notifications@github.com:

> Please update your translation of these lines if you can: 9112b22
> https://github.com/Copywrongs-Gang/Copywrongs2/commit/9112b227530d01d130cf1ab7def8ca551fc7ac4e
> 
> /cc: @pressPPGr https://github.com/pressPPGr
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Copywrongs-Gang/Copywrongs2/issues/25.

﻿title: Σώστε την μεταρρύθμιση των πνευματικών δικαιωμάτων
description: "Αυτή τη στιγμή, η ΕΕ συζητά τα σχέδια για την επιδιόρθωση των προβλημάτων που υπάρχουν με τα πνευματικά δικαιώματα και που μας επηρεάζουν κάθε μέρα. Αλλά μια ισχυρή συμμαχία από λομπίστες σαμποτάρει αυτές τις απαραίτητες ενημερώσεις. Θα έρθεις και εσύ στον αγώνα μας;"
callnow: "<span>Κάλεσε τώρα</span> για να σώσουμε αυτά τα σχέδια &ndash; θα πάρει μόνο δυο λεπτά!"
savecreform: "Σώστε<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;την μεταρρύθμιση</div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; των πνευματικών δικαιωμάτων"
daysuntil: "ημέρες μέχρι την ψηφοφορία"
rightnow: "Αυτή τη στιγμή,"
debatingplans: "η ΕΕ συζητά τα σχέδια για την επιδιόρθωση των προβλημάτων που υπάρχουν με τα πνευματικά δικαιώματα και που μας επηρεάζουν κάθε μέρα."
but: "Αλλά μια ισχυρή συμμαχία από λομπίστες σαμποτάρει αυτές τις απαραίτητες ενημερώσεις."
whichthree: "Ποιες 3 από τις παρακάτω προτάσεις είναι οι πιο σημαντικές για σένα;"
geoblocking: 
    h: "<span>Να ξεπεράσουμε</span> το geoblocking"
    cw: "Αυτό το περιεχόμενο δεν είναι διαθέσιμο στη χώρα σας."
    eu: "<strong>Κατάργηση όλων</strong> των συμβάσεων που απαιτούν από τις υπηρεσίες βίντεο να χρησιμοποιούν geoblocking, καθώς αυτού του είδους το μπλοκάρισμα είναι μια μορφή διακρίσεων στους χρήστες."
    please: "Παρακαλούμε να κρατήσουμε μια στάση ενάντια <strong>σε όλα τα είδη geoblocking</strong>, ασχέτως αν το μπλοκαρισμένο περιεχόμενο είναι αγοράσμενο άμεσα ή χρηματοδοτείται από διαφημίσεις ή από δημόσιους πόρους."
    do: Ψηφίστε τις τροπολογίες <abbr class="am" title="Καλεί για την απαλοιφή του geoblocking">#412</abbr> και <abbr class="am" title="Δηλώνει ότι το geoblocking δε θα πρέπει να αποτρέπει τις πολιτιστικές μειονότητες να έχουν πρόσβαση σε περιεχόμενο">#322</abbr> και το σημείο <span class="am">#16</span> της γνωμοδότησης της επιτροπής <abbr title="Εσωτερική Αγορά και Προστασία των Καταναλωτών">IMCO</abbr>.
    tip: "Δώστε ένα παράδειγμα που να δείχνει το πώς σας επηρεάζει το geoblocking."
extendborders: 
    h: "<span>Να επεκταθούν</span> τα δικαιώματα μας και διασυνοριακά"
    cw: "Το τι επιτρέπεται και το τι όχι, ποικίλλει σε μεγάλο βαθμό ανάμεσα στις χώρες της ΕΕ. Εάν δεν γνωρίζεις τους σχετικούς νόμους της κάθε χώρας, όταν ταξιδεύεις, μπορεί να βρεθείς σε μια κατάσταση όπου θα σε θεωρήσουν παράνομο!"
    eu: "Κάντε <strong>τις εξαιρέσεις και τους περιορισμούς</strong> για τα πνευματικά δικαιώματα <strong>υποχρεωτικές και ίδιες</strong> σε όλα τα κράτη-μέλη της ΕΕ."
    link: "https://juliareda.eu/reda-report-explained-greek/#mandatory"
    please: "Παρακαλούμε υποστηρίξτε τον <strong>εναρμονισμό των εξαιρέσεων και των περιορισμών</strong> και κάντε τες <strong>υποχρεωτικές</strong> σε όλη την ΕΕ ώστε τα δικαιώματά μου να μην περιορίζονται ή να αλλάζουν σε κάθε άλλη χώρα-μέλος."
    do: Απορρίψτε τις τροπολογίες που είναι αντίθετες στο σημείο <a class="am" href="https://juliareda.eu/reda-report-explained-greek/#mandatory" target="_blank">#11</a> της Έκθεσης της Ευρωβουλευτού Julia Reda. Υποστηρίξτε τις προσθήκες <abbr class="am" title="Καλεί για νέες υποχρεωτικές εξαιρέσεις, πχ. για το περιεχόμενο που παράγεται από χρήστες">#353</abbr>, <abbr class="am" title="Καλεί να γίνουν οι εξαιρέσεις υποχρεωτικές">#366</abbr> και το σημείο <span class="am">#15</span> της γνωμοδότησης της <abbr title="Εσωτερική Αγορά και Προστασία των Καταναλωτών">IMCO</abbr>.
protectauthors: 
    h: "<span>Προστατέψτε</span> τους δημιουργούς από τις αθέμιτες συμβάσεις"
    cw: "Οι καλλιτέχνες δεν έχουν δικηγόρους. Οι εκδότες και οι δισκογραφικές έχουν ολόκληρους στρατούς από δικηγόρους. Μαντέψτε λοιπόν ποιος έχει το πάνω χέρι στις διαπραγματεύσεις για τα συμβόλαια;"
    eu: "Προστατέψτε τους καλλιτέχνες από τις συμβάσεις που εκμεταλλεύονται καλλιτέχνες και δημιουργούς, <strong>με μια συνολική αναθεώρηση (buy-out)</strong> σε ολόκληρη την Ευρώπη θα τους επιτρέψει <strong>να πάρουν πίσω τα δικαιώματά τους</strong> σε περίπτωση που αυτά δεν χρησιμοποιήθηκαν."
    link: "https://juliareda.eu/reda-report-explained-greek/#authors"
    please: "Παρακαλούμε <strong>προστατέψετε τους καλλιτέχνες από την εκμετάλλευση</strong> και τις αθέμιτες συμβάσεις."
    do: Ψηφίστε για τη συμβιβαστική τροπολογία σχετικά με το σημείο <a class="am" href="https://juliareda.eu/reda-report-explained-greek/#authors" target="_blank">#3</a> της Έκθεσης της Ευρωβουλευτού Julia Reda και στηρίξτε τις προσθήκες με τις τροπολογίες <abbr class="am" title="Αναφέρει μια έκθεση του ΟΗΕ που τονίζει τη σημασία της προστασίας των δημιουργών">#107</abbr>, <abbr class="am" title="Ζητά για το δικαίωμα του δημιουργού να φέρνει τα έργα του στην αγορά αυτούσια στην περίπτωση που ο δικαιούχος δεν το κάνει για ένα χρονικό διάστημα">#200</abbr> και <abbr class="am" title="Ζητά το εισόδημα που συνδέεται με τις εξαιρέσεις και τους περιορισμούς (πχ. ιδιωτικές εισφορές αντιγραφής) να πηγαίνει κατευθείαν στους δημιουργούς και όχι σε άλλους δικαιούχους">#527</abbr>.
righttoquote: 
    h: "<span>Να δοθεί</span> στους vloggers το δικαίωμα να κάνουν παραπομπές"
    cw: "Το να παραθέτεις μόνο κάποιες λέξεις είναι συνήθως νόμιμο, αλλά αυτό δεν έχει επεκταθεί για να συμπεριλαμβάνει βίντεο ή/και ηχογραφήσεις -καθιστώντας έτσι τους χρήστες του YouTube και τους podcasters παράνομους."
    eu: "Οι εξαιρέσεις, όπως αυτή για την παράθεση αποσπασμάτων κειμένου, πρέπει να ισχύουν και για όλες τις μορφές πολιτιστικής έκφρασης με έναν <strong>τεχνολογικά ουδέτερο</strong> τρόπο."
    link: "https://juliareda.eu/reda-report-explained-greek/#audiovisual"
    please: "Παρακαλούμε υποστηρίξτε <strong>την επέκταση του δικαιώματος παραπομπής και στα οπτικοακουστικά μέσα</strong>."
do: Υποστηρίξτε την τροποποίηση <abbr title="Ζητά να συμπεριληφθούν οι οπτικοακουστικές παραπομπές στην υπάρχουσα εξαίρεση για τις παραπομπές" class="am">#391</abbr>
    tip: "Δώστε ένα παράδειγμα όταν κάνετε παραπομπή σε κάποιο οπτικοακουστικό μέσο ή αν είστε οπαδός των δημιουργών που κάνουν κάτι τέτοιο."
righttolink: 
    h: "<span>Υπεράσπιση</span> του δικαιώματος μας να βάζουμε συνδέσμους"
    cw: "Το διαδίκτυο υφίσταται και δομείται από/με συνδέσμους (hyperlinks). Αν όμως χρησιμοποιήσουμε συνδέσμους κάπου στο διαδίκτυο (στο blog μας, σε κάποιο post, κτλ.) αυτό μπορεί να είναι τελικά παράνομο; Οι εκδότες ειδήσεων ζητούν νόμους που να περιορίζουν το πώς οι άλλοι μπορούν να βάζουν συνδέσμους στις ιστοσελίδες τους."
    eu: "Να απορριφθούν αυτοί οι νόμοι και να διατηρήσουμε την ελευθερία στην τοποθέτηση συνδέσμων."
    link: "https://savethelink.org"
    please: "Παρακαλούμε πάρτε μια θέση ενάντια <strong>στα βοηθητικά πνευματικά δικαιώματα για τους εκδότες Τύπου</strong> τα οποία περιορίζουν τους συνδέσμους προς τα άρθρα ειδήσεων."
    do: Απόρριψη της τροπολογίας <abbr class="am" title="Ζητά την καθιέρωση ενός βοηθητικού πνευματικού δικαιώματος για τους εκδότες Τύπου">#204</abbr>. Υποστηρίξτε την συμβιβαστική τροπολογία για το σημείο <a href="https://juliareda.eu/reda-report-explained-greek/#licenses" target="_blank" class="am">#21</a> της Έκθεσης της Ευρωβουλευτού Julia Reda.
publicdomain: 
    h: "<span>Προστατέψτε</span> το Κοινό Κτήμα"
    cw: "Τα παλιά έργα τέχνης των οποίων τα πνευματικά δικαιώματα έχουν λήξει ανήκουν σε όλους μας (είναι αυτό που λέμε Public Domain/Κοινό Κτήμα). Ωστόσο, μερικοί άνθρωποι ισχυρίζονται ότι η ψηφιοποίηση τους, χορηγεί νέα πνευματικά δικαιώματα."
    eu: "Η ψηφιοποίηση των έργων που ανήκουν στο Κοινό Κτήμα δεν πρέπει να χορηγεί νέα προστασία."
    link: "https://juliareda.eu/reda-report-explained-greek/#publicdomain"
    please: "Παρακαλούμε <strong>προστατέψετε το Κοινό Κτήμα</strong> με την αποσαφήνιση ότι η δημιουργία ψηφιακού αντιγράφου ενός έργου που είναι ελεύθερο από πνευματικά δικαιώματα δεν παράγει νέα πνευματικά δικαιώματα."
    do: Ψηφίστε την συμβιβαστική τροπολογία για το σημείο <a href="https://juliareda.eu/reda-report-explained-greek/#publicdomain" target="_blank" class="am">#6</a> της Έκθεσης της Ευρωβουλευτού Julia Reda.
libraries: 
    h: "<span>Ενεργοποίηση</span> των βιβλιοθηκών για να παρέχουν τις υπηρεσίες τους και online"
    cw: "Οι βιβλιοθήκες πληρώνουν τους δημιουργούς σε αντάλλαγμα για το δικαίωμα να δανείζουν τα φυσικά αντίγραφα των βιβλίων. Αλλά το δικαίωμα αυτό δεν παρέχεται για το διαδίκτυο."
    eu: "Να επιτραπεί <strong>ο e-δανεισμός</strong>, έτσι ώστε οι βιβλιοθήκες να μπορούν να συνεχίσουν την εκπλήρωση της σημαντικής κοινωνικής λειτουργίας που επιτελούν."
    link: "https://juliareda.eu/reda-report-explained-greek/#elending"
    please: "Παρακαλούμε επιτρέψτε στις βιβλιοθήκες τον <strong>e-δανεισμό των βιβλίων</strong>."
    do: Ψηφίστε τις τροποποιήσεις <abbr class="am" title="Ζητά την υποχρεωτική επέκταση των εξαιρέσεων ώστε να συμπεριληφθούν και οι βιβλιοθήκες">#348</abbr>, <abbr class="am" title="Ζητά την ενδυνάμωση των εξαιρέσεων επ' ωφελείας του κοινού">#350</abbr> και για την συμβιβαστική τροποποίηση για το σημείο <span class="am">#20</span> της Έκθεσης της Ευρωβουλευτού Julia Reda.
publicspace: 
    h: "<span>Εξασφαλίστε</span> ότι ο δημόσιος χώρος είναι για όλους"
    cw: "Στη Γερμανία μπορείς να δημοσιεύσεις ελεύθερα τις φωτογραφίες σου από δημόσια κτίρια σε απευθείας σύνδεση (online) - αλλά πέρα από τα σύνορά της, πχ. στην Γαλλία, εκεί ο αρχιτέκτονας ενός κτηρίου θα μπορούσε να σου κάνει μήνυση!"
    eu: "Να διασφαλιστεί <strong>η ελευθερία στο πανόραμα</strong> παντού στην Ευρώπη: Η δημοσίευση εικόνων από αυτό που είναι μόνιμα σε δημόσιο χώρο σε έκθεση στο κοινό πρέπει να είναι νόμιμη. "
    link: "https://juliareda.eu/reda-report-explained-greek/#panorama"
    please: "Παρακαλούμε εξασφαλίστε την <strong>ελευθερία στο πανόραμα</strong> στην Ευρώπη, έτσι ώστε ο διαμοιρασμός φωτογραφιών από δημόσια κτήρια να είναι νόμιμος – χωρίς κάποια διάκριση για το αν είναι για εμπορική χρήση ή όχι."
    do: Απορρίψτε τις τροπολογίες που κάνουν ανίσχυρο το σημείο <a class="am" href="https://juliareda.eu/reda-report-explained-greek/#panorama" target="_blank">#16</a> της Έκθεσης της Ευρωβουλευτού Julia Reda. Ψηφίστε για το αρχικό κείμενο.
education: 
    h: "<span>Προστατέψτε</span> τις εκπαιδευτικές χρήσεις"
    cw: "Τα σχολεία μπορούν συχνά να χρησιμοποιούν ελεύθερα τα τυπωμένα βιβλία για την διδασκαλία από αυτά -αλλά αν μπει το ίδιο περιεχόμενο στο σχολικό intranet ως πχ. σε ένα αρχείο PDF αυτό θα μπορούσε να θεωρηθεί μη-τήρηση πνευματικών δικαιωμάτων."
    eu: "Χρειάζεται η εφαρμογή μιας πανευρωπαϊκής ολοκληρωμένης <strong>εξαίρεσης στα πνευματικά δικαιώματα για εκπαιδευτική χρήση</strong>."
    link: "https://juliareda.eu/reda-report-explained-greek/#education"
    please: "Παρακαλούμε υποστηρίξτε μια εξαίρεση στα πνευματικά δικαιώματα που να επιτρέπει <strong>την εκπαιδευτική χρήση</strong> υλικού με πνευματικά δικαιώματα, και στον ψηφιακό κόσμο."
    do: Υποστηρίξτε τον συμβιβασμό πάνω στο σημείο <a href="https://juliareda.eu/copyright-evaluation-report-explained/#education" target="_blank" class="am">#19</a> της Έκθεσης της Ευρωβουλευτού Julia Reda και την τροποποίηση <abbr class="am" title="Ζητά πιο ευρείες εξαιρέσεις και για τους σκοπούς της μη-τυπικής εκπαίδευσης">#364</abbr>.
availability: 
    h: "<span>Ενισχύστε</span> την διαθεσιμότητα των έργων"
    cw: "Τα πνευματικά δικαιώματα διαρκούν 70 χρόνια μετά το θάνατο του συγγραφέα. Η συντριπτική πλειοψηφία των έργων δεν είναι κερδοφόρα για τόσο μεγάλο χρονικό διάστημα – και αυτό έχει ως συνέπεια απλά αυτά να μην είναι πλέον διαθέσιμα."
    eu: "Να μειωθεί η διάρκεια των πνευματικών δικαιωμάτων στο διεθνές πρότυπο που είναι ζωή δημιουργού + <strong>50 χρόνια</strong>."
    link: "https://juliareda.eu/reda-report-explained-greek/#terms"
    please: "Παρακαλούμε υποστηρίξτε μια μείωση της <strong>διάρκειας των πνευματικών δικαιωμάτων</strong>."
    do: Υποστηρίξτε τον συμβιβασμό στο σημείο <a href="https://juliareda.eu/copyright-evaluation-report-explained/#terms" target="_blank" class="am">#7</a> της Έκθεσης της Ευρωβουλευτού Julia Reda και υποστηρίξτε το σημείο <abbr class="am" title="Καλεί για μια σημαντική μείωση της διάρκειας των πνευματικών δικαιωμάτων">#18</abbr> από την Επιτροπή <abbr title="Επιτροπή Βιομηχανία, Έρευνα και Ενέργεια">ITRE</abbr> opinion.
digitallocks: 
    h: "<span>Απορρίψτε</span> τις ψηφιακές κλειδαριές"
    cw: "Ο νόμος λέει ότι μπορείς να δημιουργήσεις αντίγραφα των μέσων που έχεις αγοράσει (CD, DVD κτλ.) για ιδιωτική χρήση - αλλά στην πράξη, οι ψηφιακές κλειδαριές συχνά δεν επιτρέπουν την αντιγραφή."
    eu: "Θα πρέπει να βεβαιώσουμε ότι τα τεχνικά μέτρα δεν θα μπορούν να περιορίζουν τα νόμιμα δικαιώματά μας."
    link: "https://juliareda.eu/reda-report-explained-greek/#drm"
    please: "Παρακαλούμε εξασφαλίστε ότι η τεχνολογική προστασία (<strong>DRM</strong>) δεν θα περιορίζει την νόμιμη χρήση του αγορασμένου περιεχομένου."
    do: Ψηφίστε το σημείο <span class="am">#26</span> της γνωμοδότησης της <abbr title="Επιτροπή Ευρωπαϊκή Αγορά και Προστασία Καταναλωτών">IMCO</abbr> και το σημείο <span class="am">#29</span> από την γνωμοδότηση της <abbr title="Επιτροπή Βιομηχανία, Έρευνα και Ενέργεια">ITRE</abbr>. Υποστηρίξτε τον συμβιβασμό στο σημείο <a href="https://juliareda.eu/reda-report-explained-greek/#drm" target="_blank" class="am">#23</a> και απορρίψτε όλες τις τροπολογίες που έρχονται σε αντίθεση με το σημείο <a href="https://juliareda.eu/reda-report-explained-greek/#drm" target="_blank" class="am">#24</a> της Έκθεσης της Ευρωβουλευτού Julia Reda (δηλ. απορρίψτε όλες τις τροπολογίες από την #549 έως και την #556).
    tip: "Δώστε ένα παράδειγμα για μια περίπτωση που το DRM στάθηκε εμπόδιο σε κάποια νόμιμη δραστηριότητα σας (πχ. να φτιάξτε αντίγραφα για προσωπική χρήση)."
filesharing: 
    h: "<span>Νομιμοποιήστε</span> την κοινή χρήση αρχείων"
    cw: "Οι έφηβοι που ανταλλάσσουν μουσική σε απευθείας σύνδεση (online) θεωρείται ότι παρανομούν από την ισχύουσα νομοθεσία. Αλλά συχνά, ένα κοινόχρηστο αρχείο δεν είναι μια χαμένη πώληση, αλλά μια δωρεάν διαφήμιση."
    eu: "Να αναγνωριστεί το δικαίωμα να μοιραζόμαστε για μη εμπορικούς σκοπούς. "
    please: "Παρακαλούμε να σταματήστε την ποινικοποίηση της προσωπικής, μη-κερδοσκοπικής <strong>κοινής χρήσης αρχείων</strong>."
    do: Ψηφίστε τις τροπολογίες <abbr class="am" title="Ζητά την διερεύνηση της νομιμοποίησης της μη-εμπορικής προσωπικής κοινής χρήσης αρχείων">#507</abbr> και <abbr class="am" title="Επιβεβαιώνει αυξητικά την νομιμότητα του διαμοιρασμού P2P">#355</abbr>.
    tip: "Δώστε ένα παράδειγμα όπου ο διαμοιρασμός ήταν ευεργετικός για τον δημιουργό, e.g. ανακάλυψες έναν δημιουργό του οποίου έγινες οπαδός και έτσι πας στις συναυλίες του και αγοράζεις τα έργα του."
currentcopywrong: "Το τρέχον πρόβλημα:"
euproposal: "Η πρόταση προς την ΕΕ:"
iwant: "Το θέλω αυτό!"
readmore: "Διαβάστε περισσότερα"
joinfight: Αν <span>δεν έρθεις και εσύ</span> μαζί σε αυτόν τον αγώνα, αυτά τα προβλήματα ("copywrongs") <u>δεν θα διορθωθούν</u>.
call:
    h: "Τηλεφώνησε τώρα για να διορθώσουμε τα πνευματικά δικαιώματα"
    text: "Το έργο των βουλευτών του Ευρωπαϊκού Κοινοβουλίου είναι <strong>να μας εκπροσωπούν</strong>.  Δεν μας αρέσει να παίρνουμε τηλέφωνο, τώρα όμως έχουμε πολλούς λόγους για τους πάρουμε τηλέφωνο και να τους <strong>ενημερώσουμε με αυτά που θέλουμε</strong>. Αν δεν το κάνουμε, η φωνή μας δεν θα ακουστεί, μόνο η φωνή από τους <strong>λομπίστες θα ακουστεί</strong> και δεν θα διορθωθεί τίποτα τελικά (και πολύ πιθανό να γίνουν τα πράγματα και χειρότερα). Πρέπει να ακουστούμε, πρέπει να φτάσει η φωνή μας στους εκπροσώπους μας για να μάθουν τι θέλουμε να κάνουν και <u>κάθε τηλέφωνο κάνει πραγματικά τη διαφορά</u>!"
    jurimember: "Μέλος της Επιτροπής Νομικών Θεμάτων"
    showother: "Επιλογή άλλου Ευρωβουλευτή"
    from: "από"
    memberstate: "ένα μέλος-κράτος της ΕΕ"
    missingstate: "το μέλος κράτος της ΕΕ δεν υπάρχει σε αυτή την λίστα λόγω του ότι δεν έχει κάποιον Ευρωβουλευτή στην Επιτροπή Νομικών Θεμάτων. Συγνώμη!"
    mynumber: "Ο τηλεφωνικός μου αριθμός:"
    other: "Άλλο"
    connectme: "Συνδέσου χωρίς χρέωση!"
    thankyou: "Ευχαριστούμε! Θα λάβεις ένα τηλεφώνημα σε πολύ λίγο."
    what: "Πώς να είναι το τηλεφώνημα;"
    agenda: "Η προσωπική σου ατζέντα:"
    agendatext: "Σχετικά με την <strong>έκθεση για τα πνευματικά δικαιώματα</strong> που θα κληθείτε να ψηφίσετε για αυτήν στην Επιτροπή Νομικών Θεμάτων στις 16 Ιουνίου..."
showmore: Για να εμφανιστούν περισσότερες προτάσεις εδώ, πάτε παραπάνω και επιλέξτε και άλλες με κλικ στο "Το θέλω αυτό!"
tell: Διαμοιράστε την είδηση
icalled: Κάλεσα τον Ευρωβουλευτή μου για να υποστηρίξω την μεταρρύθμιση στα πνευματικά δικαιώματα<br />– θα κάνεις το ίδιο;
sharetext: Επείγον, να σώσουμε την μεταρρύθμιση στα πνευματικά δικαιώματα. Κάλεσα τον Ευρωβουλευτή μου και θα πρέπει να κάνεις το ίδιο και εσύ!
credits: Η σελίδα αυτή δημιουργήθηκε από το γραφείο της <a href="https://juliareda.eu" target="_blank">Ευρωβουλευτού Julia Reda</a>, την ομάδα του <a href="http://copy-me.org/" target="_blank">Copy-Me</a> και από επιπλέον εθελοντές. <a href="https://github.com/Copywrongs-Gang/Copywrongs2">Fork it από το Github</a><br />Τα γραφικά βασίζονται εν μέρει σε εικόνες από EliRatus, useiconic.com, Cornelius Danger, Pedro Vidal, John Caserta, Carolina Andrea, Magicon, Luis Prado – όλα με άδεια Creative Commons – Attribution (CC BY 3.0)

**Comment by PeterTheOne** [comment]
Thanks!
