### ISSUE TITLE
Have a better placeholder

### ISSUE THREAD

**Issue by tttp** [Copywrongs-Gang/Copywrongs2#31]
Hi,
long time no see, we should do a hackathon again soon ;)

before you chose any mep, the default placeholder is dull:
"Photo of the MEP*
"Member of the Legal Affairs Committee"

It's probably better to either put an anonymous icon+"select your country to get an mep, or to pick up an mep
 It might be because I'm not in one of the 28 countries (do you geoip?)

Cool tool, well done! I hope you used the data from parltrack, stef would be happy ;)

**Comment by PeterTheOne** [comment]
Hi :)

It might be the "uBlock Origin" Adblock plugin.

**Comment by PeterTheOne** [comment]
It blocks http://ip-api.com/json?callback=geo I guess..

**Comment by tttp** [comment]
It might be because I'm in CH too

X+

**Comment by PeterTheOne** [comment]
@tttp: It should be fixed now, can you please check? ^^
