### ISSUE TITLE
"lsr" is hardcoded in _layouts/default.html

### ISSUE THREAD

**Issue by tfla** [Copywrongs-Gang/Copywrongs2#37]
Here's a diff that would mitigate that, could send a PR if you want. Would also require new translations.

Not sure where this issue stems from, and I'm too lazy to see the commit log or bisect.

diff: http://sprunge.us/fhQh

**Comment by PeterTheOne** [comment]
it's the last day anyway :P

**Comment by tfla** [comment]
Yeah, I just noticed it last night. :P Seems the vote went pretty well with a few exceptions. Good work everyone <3

**Comment by PeterTheOne** [comment]
:) you did good work also!
